### ISSUE TITLE
Please give env file

### ISSUE THREAD

**Issue by VanshajPoonia** [live-codes/livecodes#204]
Can you guys please provide the env file?

**Comment by hatemhosny** [comment]
There is actually no env file!

the variables are added to `process.env` during build
these are defined [here](https://github.com/live-codes/livecodes/blob/develop/scripts/build.js#L28-L39)
and made available to esbuild [here](https://github.com/live-codes/livecodes/blob/develop/scripts/build.js#L49-L59)
are then are used [here](https://github.com/live-codes/livecodes/blob/develop/src/livecodes/core.ts#L1127-L1139)

they essentially show (in the browser console) the version and the git commit with links to them on GitHub, if you add the querystring `?showVersion`, like that:
https://livecodes.io/?showVersion

does that answer your question?
feel free to ask if you need more info

**Comment by VanshajPoonia** [comment]
Hey!
Thanks a lot but when I am trying to deploy it via the digitalocean deploy button that is given in the readme file. I am receiving an error message on Digitalocean stating "GitHub user does not have access to hatemhosny/livecodes"

**Comment by hatemhosny** [comment]
The "Deploy to DigitalOcean" button seems to stopped working.
I have removed it from the readme.
you may refer to "[Getting started](https://github.com/live-codes/livecodes#getting-started)" section for other options
