### ISSUE TITLE
Keeping the scroll position after reload

### ISSUE THREAD

**Issue by jinhojang6** [live-codes/livecodes#297]
First of all, thanks for the awesome project. This is such impressive work and the team is doing great work for people all over the world.

I found that when I update the code on the left panel, the right panel is automatically reloaded and scrolled to top.

Is it possible to keep the scroll position after the reload? For example, if a user is seeing a section from 1000px from the top and update the code, the reloaded page shows the same section (1000px from the top) so that I can find what's changed without scrolling down the right panel.

Currently, I've added
```
document.addEventListener("DOMContentLoaded", function(event) { 
            var scrollpos = localStorage.getItem('scrollpos');
            if (scrollpos) window.scrollTo(0, scrollpos);
        });

        window.onbeforeunload = function(e) {
            localStorage.setItem('scrollpos', window.scrollY);
        };
```
to the JS code manually to keep the scroll.

Thank you

**Comment by jinhojang6** [comment]
Thanks for the feedback @hatemhosny 

1. I'm using https://livecodes.io/ but the scroll position is not fixed here as well. Isn't https://livecodes.io/ production mode?

2. What you said makes sense and I respect the direction. But from a users' point of view, it would be better to find what's updated without scrolling down to the changed section. I think there could be a prop to enable this. (e.g., fixedScrollPosition)

Thanks and looking forward to updates!

**Comment by aehlke** [comment]
I'll note that it's the default behavior of Safari to preserve scroll position on page reload, without preserving form inputs.

**Comment by hatemhosny** [comment]
@jinhojang6 
Now the result page scroll position is maintained after reload.

I do not use localstorage so as not to affect other projects.

The app keeps track of the result page scroll position and when it reloads, the position is sent to the new page.

Scroll position is reset if a new project is loaded.

This behavior only works inside the playground. If the result page is exported, this does not occur.

This behavior can be disabled by the query param:  
`?scrollPosition=false`

You may test this in https://dev.livecodes.io 

It is documented in https://dev.livecodes.io/docs/features/result#scroll-position

Thank you for reporting that.  
Please let me know if this solves your problem.
