### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jinhojang6** [live-codes/livecodes#298]
On top of the issue below, I got these problem during `npm install`

1. @types/jest
```
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/jest@"^27.0.0" from ts-jest@27.1.3
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"27.1.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @types/jest@27.5.2
npm ERR! node_modules/@types/jest
npm ERR!   peerOptional @types/jest@"^27.0.0" from ts-jest@27.1.3
npm ERR!   node_modules/ts-jest
npm ERR!     dev ts-jest@"27.1.3" from the root project
```

2. after removing `@types/jest` from package.json, got a problem with `esbuild`.

3. after removing `esbuild` from package.json, got a problem with `@codemirror/comment@^6.0.0`.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @codemirror/comment@^6.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

It finally worked after removing `@replit/codemirror-vscode-keymap` and `playwrite` from package.json.

**Comment by hatemhosny** [comment]
`npm install` should work without having to remove dependencies. (e.g. esbuild is essential for building the project)

just make sure that [package-lock.json](https://github.com/live-codes/livecodes/blob/develop/package-lock.json) is present when installing.

typically you would run:

```sh
# clone repo
git clone https://github.com/live-codes/livecodes

# move to directory
cd livecodes

# install dependencies
npm install

# build
npm run build

# serve the app
npm run serve

# develop (serve & watch changes)
npm start
```
