### ISSUE TITLE
Adjust layout?

### ISSUE THREAD

**Issue by moonpiedumplings** [live-codes/livecodes#343]
Is there anyway to have the console/results display below the editor, rather than alongside it?

**Comment by hatemhosny** [comment]
@moonpiedumplings 
Currently this is not supported, however it may be supported later.

What is your use case:
- app?
- app on mobile?
- embedded playgrounds?

**Comment by moonpiedumplings** [comment]
I want to embed playgrounds into my blog, which is read from top to bottom. 

https://moonpiedumplings.github.io/quartotest/posts/interactive-python-tutorial/.

**Comment by adamgreenough** [comment]
+1 for this! A nicer responsive experience for code examples & results together would be awesome :)

**Comment by hatemhosny** [comment]
This has now been [released in v27](https://github.com/live-codes/livecodes/releases/tag/v27).
