### ISSUE TITLE
Feature: Editor Themes

### ISSUE THREAD

**Issue by adamgreenough** [live-codes/livecodes#414]
### Type of feature

✨ Feature

### Suggested feature

Ability to select editor themes for the editor and embeds or configure custom ones in file system

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
Hi @adamgreenough 
Ability to select editor theme is planned.

However, configuring custom themes for code editors is much more involved. Considering there are 3 different code editors (Monaco, CodeMirror6 & CodeJar/Prism).

So probably the planned approach is selecting one of predefined themes for each code editor with fallback default theme for light and dark modes.

**Comment by hatemhosny** [comment]
Please let me know of preferred themes for any of these editors that you want to support.

**Comment by adamgreenough** [comment]
Monaco themes: https://github.com/brijeshb42/monaco-themes/tree/master/themes
CodeMirror themes: https://codemirror.net/5/demo/theme.html
Prism themes: https://github.com/PrismJS/prism-themes/tree/master/themes

I'd love to be able to pick from the selection of these depending on the editor selected, especially that they carry through to the embeds so it can match a users site.

**Comment by adamgreenough** [comment]
Got it! Looks like there are several pre-made CM6 themes available here: https://github.com/craftzdog/cm6-themes

**Comment by hatemhosny** [comment]
@adamgreenough 
this has now been implemented in #483 
the links you sent were indeed very helpful

This should be available in next release. However,  you may try it on https://next.livecodes.io/?screen=editor-settings

Thank you ♥️
