### ISSUE TITLE
Feature: Global Themes

### ISSUE THREAD

**Issue by adamgreenough** [live-codes/livecodes#415]
### Type of feature

✨ Feature

### Suggested feature

Ability to load/inject custom CSS to style the UI and embed interfaces themselves without editing core files that will be replaced in an update

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
The ability to add custom themes for the playground UI is planned and probably soon.

The approach I plan is the ability to supply a JSON object (or URL) with values for CSS variables which are [already being used](https://github.com/live-codes/livecodes/blob/f2d6ff29e0721c43b4e09d0f920ce87f64f46bc9/src/livecodes/styles/app.scss).

This is a lot more controlled than arbitrary CSS that may mess with layout. 

This would be different

**Comment by adamgreenough** [comment]
Awesome! Thanks for bringing those CSS variables to my attention, I might try and fork changing just those and rebuilding for updates for now. 

Really excited to see where this project goes. A game changer for code documentation and blogging where I can be in control of my own embeds. :)

**Comment by hatemhosny** [comment]
For custom themes, I may need to add/split some CSS variables. But, yes, you may give it a try as a start.

**Comment by hatemhosny** [comment]
Closed by #630
