### ISSUE TITLE
Bug: build/index.html not getting patched with build hash

### ISSUE THREAD

**Issue by aehlke** [live-codes/livecodes#436]
### Describe the bug

From build/index.html:
`    <script src="livecodes/{{hash:index.js}}"></script>`

Other files have their hash patterns replaced properly.

### Steps to reproduce

`DOCS_BASE_URL=null npm run build`

### Affected services

Repo build/deploy

### Is it already fixed?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
Weird!

This would cause the playground to not load at all, which would cause all e2e tests to fail. I have not had this issue, neither locally or on other [environments](https://github.com/live-codes/livecodes/actions) (github actions, cloudflare pages, netlify, github pages)

Does that happen every time or is it flacky?

Any console errors?

Are you using the latest commit?

Also, if you do not want to build the docs, you should use this command instead (as stated [here](https://livecodes.io/docs/features/self-hosting#custom-build))

```shell
DOCS_BASE_URL=null npm run build:app
```

**Comment by hatemhosny** [comment]
I assume this is no longer a problem.
I will close this for the sake of organization.
Please feel free to re-open it if you still face this problem.

**Comment by aehlke** [comment]
I'll reopen if/when I revisit - I'm just using a fork at an old version for now but will update later and try again, thx
