### ISSUE TITLE
Monaco editor CSS nesting support

### ISSUE THREAD

**Issue by gapmiss** [live-codes/livecodes#515]
Currently, the monaco editor shows errors when using CSS nested selectors.

![CleanShot-Obsidian-View Transitions test + vtremove prototype - Playground - Obsidian v1 5 8-2024-02-23-13 13 25](https://github.com/live-codes/livecodes/assets/98914514/504add9d-64cd-4291-8e55-6172df87e0bb)

Is it possible to update the engine to remove these errors? Are there any SDK config options that might solve this issue?

After a brief search, this may be related to my request.

https://github.com/microsoft/monaco-editor/issues/4071

Thank you!

**Comment by hatemhosny** [comment]
Thank you for raising that up and for the helpful link.

I will watch that issue in Monaco editor till supported and update it.

May be a temporary solution is loading CSS in Monaco editor as SCSS (which is a superset of CSS). Of course, the SCSS compiler will not be used in that case.
What do you think?

**Comment by gapmiss** [comment]
Your temp solution works great. Thank you for the tip!

**Comment by hatemhosny** [comment]
@gapmiss 

I have implemented this workaround. (use SCSS language in Monaco instead of CSS, till official support lands)

Please try it on this preview URL and let me know if you have any comments:
https://48652ce8.livecodes.pages.dev/

![image](https://github.com/live-codes/livecodes/assets/10176547/3b90c07e-4119-4087-9e40-0fd3ac5586a6)

Thank you for reporting this issue.

**Comment by hatemhosny** [comment]
> @hatemhosny
> 
> Yes, this works great. Thank you
> 
> I was also hoping it would solve similar issues with CSS `@layer`. However, even with your SCSS workaround, it still show errors. Not sure if they are similar, but am happy to have the nesting workaround.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
> 
> ![CleanShot-Safari-LiveCodes-2024-02-26-07 23 40](https://private-user-images.githubusercontent.com/98914514/307783089-3335376e-5660-4f90-87ea-9c1b2955fca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzczMTAsIm5iZiI6MTcwOTE3NzAxMCwicGF0aCI6Ii85ODkxNDUxNC8zMDc3ODMwODktMzMzNTM3NmUtNTY2MC00ZjkwLTg3ZWEtOWMxYjI5NTVmY2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAzMjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwM2I2YTExMGI4ZGRhYjVhOWU5NTdjZmM0NDdiOGE0YjliMzY4NWY1MjVmMWY4NGVjOWY3NjQyNDQ4OWRlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBbbyNCDaBQL1pEzRKuSHxL2KYWUtrAb8KjFB3-yuwU)

@gapmiss 
we need to wait for monaco to support that
the css nesting workaround has been merged and should be available in next release
meanwhile, you may test it on https://next.livecodes.io/
thank you for reporting

**Comment by gapmiss** [comment]
@hatemhosny agree, best choice at the moment ... thank you

**Comment by hatemhosny** [comment]
hi @gapmiss 

CSS nesting & `@layer` are now supported on Monaco editor

![image](https://github.com/live-codes/livecodes/assets/10176547/4c1b3165-f195-41d0-b44a-fd5dc35e3dc5)

demo:
https://livecodes.io/?x=id/hjqjv3avhkh


![image](https://github.com/live-codes/livecodes/assets/10176547/73741381-f7bd-4147-9802-6a2801019ad4)

demo: https://livecodes.io/?x=id/35w66b2vbdk

Thank you :)
