### ISSUE TITLE
polyfill.io concerns

### ISSUE THREAD

**Issue by gapmiss** [live-codes/livecodes#519]
I've noticed (via Little Snitch firewall) that Livecodes will sometimes load javascript from `pollyfill.io` and recently saw this tweet from [@wesbos](https://twitter.com/wesbos/status/1762133691906547850).

![CleanShot-NetNewsWire-twitter-2024-02-27-19 03 00](https://github.com/live-codes/livecodes/assets/98914514/0ca20d23-88c0-4fd8-91d3-c26bc227d4e3)

Also: https://github.com/polyfillpolyfill/polyfill-service/issues/2834

~~Is this the same polyfill that Livecodes uses?~~ I did a search for `pollyfill.io` and found the script tag.

https://github.com/live-codes/livecodes/blob/367fa259da25e690a55eb37d72285d6cd30a48e7/src/livecodes/html/app.html#L198

Thank you

**Comment by hatemhosny** [comment]
Thank you @gapmiss for raising this.

I have also found that Cloudflare has published a fork
https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk

This might be more suitable for LiveCodes since it is already hosted on Cloudflare

**Comment by hatemhosny** [comment]
FYI

https://sansec.io/research/polyfill-supply-chain-attack
https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/
