### ISSUE TITLE
Feature: Displaying results in the order they were generated

### ISSUE THREAD

**Issue by adrianolszewski** [live-codes/livecodes#533]
### Type of feature

✨ Feature

### Current behavior

Hello!
First of all - thank you very much for so awesome project, ideal for learning and "sandboxed" experimenting!

I noticed that when using the R template (I did not test other languages), the results are printed in the following way: text results first then figures.

Like in the picture below:
![obraz](https://github.com/live-codes/livecodes/assets/95669100/23069812-5ff4-48b3-a5bb-230b42cc9bd2)

### Suggested feature

I think it would be more natural if the results were displayed in the order they were generated. It would be much easier to match the code and the results. A bit like in the markdown.

So, for the given code: 
```
1
[figure]
a vector of numbers
2
[figure]
3
a vector of numbers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
Thank you @adrianolszewski for reaching out. I'm glad you like LiveCodes.

This behavior is a limitation in [WebR](https://docs.r-wasm.org/webr/latest/) (the engine that LiveCodes uses to run R in the browser). Code evaluation comes in a different output from plots.

However, LiveCodes allows you to have some control (using helper JavaScript) on where to put the code/plot output in the result page. See details and examples in LiveCodes [R language documentations](https://livecodes.io/docs/languages/r/#output-rendering). This may not be exactly what you are asking for, but it gives you more control. 

Please let me know if you need more information.

**Comment by adrianolszewski** [comment]
Ah! Got it! So the different types of results go into separate "outputs", like in R (console vs. graphics window) or RStudio (different "panels"). Now it makes sense. I need to check if the R code can be run "synchronously", part by part, so the outcomes of certain type could be ordered similarly to RMarkdown/R notepad. Thank you very much for the explanation!
