### ISSUE TITLE
Feature: add event to SDK watch method

### ISSUE THREAD

**Issue by gapmiss** [live-codes/livecodes#534]
### Type of feature

✨ Feature

### Current behavior

Currently, in an embedded playground, when the "External Resources" modal is opened and modified ("Load" button clicked), there is no event to listen for.

### Suggested feature

Add new event (External Resources changed) to the watch() method - https://livecodes.io/docs/sdk/js-ts/#watch so that a local config can be updated and playground refreshed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
@gapmiss good catch (as usual!)
I will add something like that 👍
Thank you.

**Comment by hatemhosny** [comment]
@gapmiss 

The SDK [watch](https://livecodes.io/docs/sdk/js-ts#watch) method allows you to run the callback functions registered to `code` event when playground "content" changes. This currently include changes in:
- code (in editors)
- editor languages
- project info (which allows adding content in page head and attributes to `html` element)
- custom settings (e.g. allows changing import maps)
- project title
- test code

I missed firing that event with changes in external resources.

I believe it makes sense to associate the same event (`code`) with changes in external resources (`stylesheets`, `scripts`, `cssPreset`). Please note that the callback function allows accessing the changed [`Code`](https://livecodes.io/docs/api/interfaces/Code) and [`Config`](https://livecodes.io/docs/api/interfaces/Config) (which has the changed resources).

You can always know what changed by comparing the `Config` before and after the event.

Does that cover your use-case?

**Comment by hatemhosny** [comment]
@gapmiss 
you may try it on this preview URL: https://watch-external-resources.livecodes.pages.dev/

also added a note about sources of change for `code` event in docs: https://watch-external-resources.livecodes.pages.dev/docs/sdk/js-ts#watch

**Comment by gapmiss** [comment]
@hatemhosny

This is great. Am already watching for `code` changes, so your preview `appUrl` worked straight away.

… and the documentation, first-class as always!

Thank you for your attention to details and accommodating my request so quickly.

**Comment by hatemhosny** [comment]
@gapmiss 
Great. This has now been merged and should be available in next release. 
Thank you for reporting 💚.

By the way, great work with the Obsidian plugin. 👍
I posted about it on Twitter here:
https://x.com/hatem_hosny_/status/1769893392463401375?s=20

**Comment by gapmiss** [comment]
@hatemhosny

My pleasure!

Appreciate the complement, still a work in progress, but am happy with the results so far. Hope others will find it useful in their development journeys. I have many more ideas on use cases, publishing, sharing, etc.

For testing the plugin and learning, I've accumulated a library of over 3,200 playgrounds over the last 6+ months. I've really been putting Livecodes thru the "ringer." I do have some questions that have arisen from so much testing… but for another day.

Thank you for the shout-out on Twitter. I'm not on Twitter (at the moment) but am on Mastadon. Have you considered joining/posting to Mastadon? Quite a decent developer community present on Mastadon and I would definitely "boost" your posts if you chose to do so. This morning, I helped someone with a CSS question and posted a demo on Livecodes. Check it out: https://thoresson.social/@anders/112144602797874363

Until next time, all the best to you!

**Comment by hatemhosny** [comment]
@gapmiss 
Thank you, indeed.
I would be very interested to know your comments/questions. I'm sure that would be very valuable.
I'm not currently active on Mastodon. I will let you know if I start being active there. 
Thank you.

**Comment by hatemhosny** [comment]
@gapmiss 
This had now been [released in v27](https://github.com/live-codes/livecodes/releases/tag/v27).
Credit was given to you in release notes and on [Twitter announcement](https://x.com/hatem_hosny_/status/1780407742101950598).
Thank you 💚
