### ISSUE TITLE
Bug: Can not add extern resources to react starter project

### ISSUE THREAD

**Issue by dwina** [live-codes/livecodes#535]
### Describe the bug

If I try to add a extern resource for e.g. jquery I get the following error. "Failed to load results!". So in my case I tried to get run material-ui with a simple Button. Without any success. I tried another way like through a cdn provider but not worked too. I try to  fetch the material ui library via npm. All not worked. 

### Steps to reproduce

I download the livecodes-v26.zip and unzip in my file server (tomcat 10.1). When I use the the template "React Starter" where I tried to import the material-ui library in my project

### Affected services

LiveCodes App

### Platforms

Desktop

### Browsers

Chrome

### Environment

Self-Hosted

### Is it already fixed?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
Thank you @dwina 

material-ui dependencies were not resolved correctly.

However, I followed their example loading the library from CDN.
This is a working example:
https://livecodes.io/?x=id/sh8c9nsb9j6

please let me know if this solves your problem.

**Comment by dwina** [comment]
thank you for the fast answer and the good example. It worked now fine by me

**Comment by hatemhosny** [comment]
Great.
I will close this now.
