### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by hatemhosny** [live-codes/livecodes#548]
### Discussed in https://github.com/orgs/live-codes/discussions/547

<div type='discussions-op-text'>

<sup>Originally posted by **zyf722** April  5, 2024</sup>
> I'm working on a project that requires me to allow users to edit and run code in multiple languages in the browser. Then I found this project and it works perfectly for my needs.

> I notice that currently all messages and texts are hardcoded in the source code. I think it would be better if we can move all these texts to a separate file so that it's easier to maintain and translate. Any plans or thoughts on this i18n feature?</div>

This is also related to providing a RTL layout, since a significant percentage of LiveCodes users have Arabic as their first language.

**Comment by zyf722** [comment]
.take
