### ISSUE TITLE
Bug:  External Resources cannot be loaded in Firefox

### ISSUE THREAD

**Issue by scheibome** [live-codes/livecodes#628]
There seems to be a cross-origin resource sharing problem in Firefox. It is not possible to load external resources.

Screenshots:
Chrome - Works
Firefox - Error

![SCR-20240817-lrhc](https://github.com/user-attachments/assets/deab94d4-5c47-4389-8801-ac8f0c789fce)
![SCR-20240817-lroc](https://github.com/user-attachments/assets/d70d649a-5b53-4983-a09b-29b26099201f)

**Comment by hatemhosny** [comment]
Thank you, @scheibome for reporting this.

An explanation of the problem and a fix are provided by PR #629

This should be available in the next release.

Meanwhile, you can try it in the development build on: https://dev.livecodes.io/

Thank you 💚

**Comment by scheibome** [comment]
That looks really good. 👍🏻
