### ISSUE TITLE
CSS icons fallback

### ISSUE THREAD

**Issue by hatemhosny** [live-codes/livecodes#652]
### Type of feature

✨ Feature

### Current behavior

hey @gigamaster 

I really like the CSS icons you introduced. 
I just noticed that [CSS masking](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) has [baseline compatibility](https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility): "newly available".

I generally target this compatibility level for the full app since the users are developers I expect them to have updated browser versions.
However, for embeds I aim to target compatibility level: "widely available" since the users might be less tech-savvy or running in more restricted environments.

In this situtation I prefer to provide fallbacks to make it usable even for older browsers.
CSS isons are used in embeds.

### Suggested feature

I'm suggesting a fallback based on your code to use the svg as a background image instead of masks and use invert filter to show hover/active state for light and dark themes.

This would be placed in a `@supports` block to only work if masks are not supported.
It should otherwise require no code changes.

The icons should appear (without the theme color), but respond with shades of grey on hover/active and for dark/light themes.

This is a demo for the suggestion (icon size is enlarged for the demo): https://livecodes.io/?x=id/ncvsjhnzvep

Please let me know what you think.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
If you agree with the approach, I can start a PR with the proposed changes.

**Comment by gigamaster** [comment]
@hatemhosny 
I haven't had any problems using mask. Over the last few years, major browsers implemented `mask` so quickly that I've stripped out prefixes, e.g. -web-kit, down to the things that matter. But the way you're extending support seems good.

**Comment by hatemhosny** [comment]
> @hatemhosny I haven't had any problems using mask. Over the last few years, major browsers implemented `mask` so quickly that I've stripped out prefixes, e.g. -web-kit, down to the things that matter. But the way you're extending support seems good.

Thank you @gigamaster 

I really like the mask approach. Very neat.

I just think that this addition is an easy win since it adds very little code and might extend support as you say.

By the way, LiveCodes [build pipeline](https://github.com/live-codes/livecodes/blob/develop/scripts/styles.js) uses autoprefixer, so you don't need to manually add vendor prefixes anyway, even for other features.
