### ISSUE TITLE
Feature: Catppuccin Color Scheme

### ISSUE THREAD

**Issue by Shlok-Bhakta** [live-codes/livecodes#686]
### Type of feature

🎨 Style

### Suggested feature

The [catppuccin color scheme](https://catppuccin.com/) for the editor would be super cool. I like the pastel colors and my whole system is themed to catppuccin. I can give my best shot at implementing this, where would I begin adding the theme options? Is there a style.css file for codejar, codemirror, and monaco that I can edit? Thanks!

The scope of the change is that there are 4 new themes in the editor theme picker preferably for all 3 of the editor types. If that is not possible, I will prioritize codejar
- Catppuccin Latte
- Catppuccin Frappe
- Catppuccin Macchiato
- Catppuccin Mocha

Please let me know of anything I should look out for. Like if I need to add the themes anywhere else in the typescript or if there is other stuff that needs to be done after adding css.

### Additional context

https://catppuccin.com/palette - Here are the color pallets. 

Ill be looking at their style guide for implementation of colors - https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
hi @Shlok-Bhakta 

Thank you for the nice suggestion. 
I agree, this would be a nice addition to the themes available in LiveCodes.

Yes, please. Go ahead implementing that if you like. I would be very grateful.
You can find the theme definitions for the code editors here:

- [Monaco](https://github.com/live-codes/livecodes/blob/develop/src/livecodes/editor/monaco/monaco-themes.ts)
- [CodeMirror 6](https://github.com/live-codes/livecodes/blob/develop/src/livecodes/editor/codemirror/codemirror-themes.ts)
- [CodeJar](https://github.com/live-codes/livecodes/blob/develop/src/livecodes/editor/codejar/prism-themes.ts) (uses Prism.js themes)

You may just follow the pattern for adding themes for each editor. Please let me know if you need any guidance.
Thank you :)

**Comment by hatemhosny** [comment]
Closed by 688
