### ISSUE TITLE
Feature: Auto format on save option

### ISSUE THREAD

**Issue by AhmedAdel991** [live-codes/livecodes#690]
### Type of feature

✨ Feature

### Current behavior

Currently there is no option to enable auto format on save

### Suggested feature

Add a checkbox in the options panel to enable auto format on save

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by AhmedAdel991** [comment]
Sorry, I just noted the format option has a shortcut which makes this feature obsolete.

**Comment by hatemhosny** [comment]
Thank you @AhmedAdel991 

There is indeed a "Format On-save" option, which you can find in the settings menu. It is disabled by default. But once you enable it, the setting will be remembered across your sessions.

Please note that format will not be triggered automatically if you enable "Auto Save" unless you manually save the project (e.g. from project menu or the shortcut Ctrl + S)

![image](https://github.com/user-attachments/assets/07017e66-8d17-4c06-b2b9-793dec6d26da)

And yes, the keyboard shortcut "Alt + Shift + F" triggers code format :)

Please let me know if you have any other questions or comments.
Thank you.

**Comment by AhmedAdel991** [comment]
Thanks DR. @hatemhosny for your great work, no that would be all shall I close the issue?

**Comment by hatemhosny** [comment]
> Thanks DR. @hatemhosny for your great work, no that would be all shall I close the issue?

You are most welcome. 
Yes, please, you may close this if you have no further inquiries.
